<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/10_%ED%96%89%EA%B3%BC_%EC%97%B4_%EB%B3%80%ED%99%98%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})
df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

**모든 열을 행으로 변환하기**

In [ ]:
pd.melt(df)

  variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

**하나의 열만 행으로 이동시키기**

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B'])  # A열만 그대로, B열은 행으로 이동

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

**여러 개의 열을 행으로 이동시키기**

In [ ]:
df_melt= pd.melt (df, id_vars=['A'], value_vars=['B','C'])  # A열만 그대로, B열과 C열은 행으로 이동
df_melt

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

**특정 열의 값을 기준으로 새로운 열 만들기**

In [ ]:
df_pivot = df_melt.pivot(index='A', columns='variable', values='value')  # A열은 새로운 인덱스로 만들고, B열과 C열은 이에 따라 정리
df_pivot

variable  B  C
A
a         1  2
b         3  4
c         5  6

**원래 데이터 형태로 되돌리기**

In [ ]:
df_origin = df_pivot.reset_index()  # 인덱스를 리셋함
df_origin.columns.name = None  # 인덱스 열의 이름을 초기화함
df_origin

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6