<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/1.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EB%A7%8C%EB%93%A4%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**STEP 1. 판다스 라이브러리 불러오기**

In [ ]:
import pandas as pd

**STEP 2. 데이터 프레임 만들기**

   **인덱스가 1개일 때**

In [ ]:
df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=[1,2,3,4]
     )

# 데이터 열 이름을 따로 지정해서 만들 수도 있음
df = pd.DataFrame(
    [[4, 5, 6, 7],
     [8, 9, 10, 11],
     [12, 13, 14, 15]],
     index=[1,2,3,4],
     columns=['a', 'b', 'c'])

df

   a   b   c
1  4   8  12
2  5   9  13
3  6  10  14
4  7  11  15

**인덱스가 2개일 때**

In [ ]:
df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)

df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15