<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/1%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C3_%EC%9D%B4%EC%B1%84%EB%A6%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
data = sns.load_dataset('diamonds')

##head를 이용해 데이터를 잘불러왔는지 확인해보자

In [ ]:
data.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

##데이터 정보를 확인해보자

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

##위에서부터 10개의 아이템 출력

In [ ]:
data.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

##아래에서부터 10개의 아이템 출력

In [ ]:
data.tail(10)

       carat        cut color clarity  depth  table  price     x     y     z
53930   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53934   0.72    Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

##color column의 class를 확인해보자

In [ ]:
data['color'].unique()

['E', 'I', 'J', 'H', 'F', 'G', 'D']
Categories (7, object): ['D', 'E', 'F', 'G', 'H', 'I', 'J']

##color가 F인 item의 개수를 확인해보자

In [ ]:
len(data.loc[data['color']=='F'])

9542

##x > 10, y > 10인 데이터 행을 출력해보자

In [ ]:
data[data['x']>10][data['y']>10]

<ipython-input-9-b5d6a7009749>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[data['x']>10][data['y']>10]

       carat      cut color clarity  depth  table  price      x      y     z
25998   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
27415   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27630   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72

##가격이 가장 비싼 10개의 보석을 출력해보자

In [ ]:
data.nlargest(10,'price')

       carat        cut color clarity  depth  table  price     x     y     z
27749   2.29    Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16
27748   2.00  Very Good     G     SI1   63.5   56.0  18818  7.90  7.97  5.04
27747   1.51      Ideal     G      IF   61.7   55.0  18806  7.37  7.41  4.56
27746   2.07      Ideal     G     SI2   62.5   55.0  18804  8.20  8.13  5.11
27745   2.00  Very Good     H     SI1   62.8   57.0  18803  7.95  8.00  5.01
27744   2.29    Premium     I     SI1   61.8   59.0  18797  8.52  8.45  5.24
27742   2.04    Premium     H     SI1   58.1   60.0  18795  8.37  8.28  4.84
27743   2.00    Premium     I     VS1   60.8   59.0  18795  8.13  8.02  4.91
27740   1.71    Premium     F     VS2   62.3   59.0  18791  7.57  7.53  4.70
27741   2.15      Ideal     G     SI2   62.6   54.0  18791  8.29  8.35  5.21

##가격이 가장 싼 10개의 보석을 출력해보자

In [ ]:
data.nsmallest(10,'price')

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

##E color를 가진 가장 비싼 보석 5개를 출력해보자

In [ ]:
data[data['color']=='E'].nlargest(5,'price')

       carat        cut color clarity  depth  table  price     x     y     z
27720   2.02  Very Good     E     SI1   59.8   59.0  18731  8.11  8.20  4.88
27688   1.51      Ideal     E     VS1   61.5   57.0  18729  7.34  7.40  4.53
27683   2.00  Very Good     E     SI1   60.5   59.0  18709  8.09  8.14  4.94
27677   1.28      Ideal     E      IF   60.7   57.0  18700  7.09  6.99  4.27
27637   1.72  Very Good     E     VS2   63.4   56.0  18557  7.65  7.55  4.82

##x가 가장 큰 10개 보석들 중 y값이 가장 작은 값 5개를 출력해보자

In [ ]:
data.nlargest(10,'x').nsmallest(5,'y')

       carat      cut color clarity  depth  table  price      x     y     z
22741   3.01     Fair     H      I1   56.1   62.0  10761   9.54  9.38  5.31
24328   3.50    Ideal     H      I1   62.8   57.0  12587   9.65  9.59  6.03
27679   3.51  Premium     J     VS2   62.5   59.0  18701   9.66  9.63  6.03
26534   3.67  Premium     I      I1   62.4   56.0  16193   9.86  9.81  6.13
27130   4.13     Fair     H      I1   64.8   61.0  17329  10.00  9.85  6.43

##z값이 가장 큰 보석들 10개를 가격이 높은순으로 정렬해서 출력해보자

In [ ]:
data.nlargest(10,'z').sort_values('price',ascending=False)

,carat,cut,color,clarity,depth,table,price,x,y,z
27630,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72
27415,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98
27130,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43
26444,4.00,Very Good,I,I1,63.3,58.0,15984,10.01,9.94,6.31
26431,3.40,Fair,D,I1,66.8,52.0,15964,9.42,9.34,6.27
25999,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24
25998,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17
24067,2.00,Premium,H,SI2,58.9,57.0,12210,8.09,58.90,8.06
23644,3.65,Fair,H,I1,67.1,53.0,11668,9.53,9.48,6.38
48410,0.51,Very Good,E,VS1,61.8,54.7,1970,5.12,5.15,31.80

##20개의 데이터를 임의로 뽑아보자

In [ ]:
samples = data.sample(n=20)
samples

       carat        cut color clarity  depth  table  price     x     y     z
7214    1.01    Premium     H     SI1   61.9   59.0   4191  6.35  6.32  3.92
52039   0.71       Good     D     SI1   56.8   62.0   2450  5.93  5.89  3.37
52475   0.73    Premium     D     SI2   62.4   58.0   2519  5.72  5.67  3.56
10092   0.90       Good     F     SI1   63.6   55.0   4712  6.15  6.12  3.90
43166   0.42      Ideal     D    VVS2   62.5   57.0   1389  4.80  4.77  2.99
34002   0.42  Very Good     G     VS2   62.6   57.0    847  4.76  4.80  2.99
24063   1.33      Ideal     G    VVS2   62.6   57.0  12209  7.04  6.99  4.39
6965    1.01       Good     E     SI2   63.3   58.0   4149  6.29  6.35  4.00
42234   0.40      Ideal     E     VS1   61.1   57.0   1291  4.75  4.78  2.97
44291   0.52    Premium     G     VS2   62.4   56.0   1577  5.19  5.16  3.23
20535   1.11      Ideal     G    VVS2   61.8   57.0   8858  6.67  6.64  4.11
5530    0.91    Premium     H     VS2   59.6   60.0   3853  6.29  6.25  3.74
21899   1.20  Very Good     G    VVS1   61.8   55.0   9968  6.79  6.83  4.21
18556   1.01      Ideal     E     VS1   61.6   57.0   7565  6.45  6.41  3.96
23025   0.30  Very Good     G    VVS2   60.3   57.0    631  4.35  4.36  2.63
24159   2.01      Ideal     I     SI2   62.1   57.0  12338  8.07  8.03  5.00
29183   0.30      Ideal     F    VVS2   62.5   56.0    694  4.28  4.33  2.69
46168   0.50    Premium     E     VS2   61.3   60.0   1746  5.11  5.07  3.12
8131    1.01    Premium     E     SI2   62.5   60.0   4355  6.39  6.42  4.00
29534   0.30  Very Good     F     VS1   60.9   63.0    704  4.26  4.31  2.61

##뽑은 데이터의 index를 초기화시켜보자(Tip. drop=True)

In [ ]:
samples.reset_index(drop=True)

    carat        cut color clarity  depth  table  price     x     y     z
0    1.01    Premium     H     SI1   61.9   59.0   4191  6.35  6.32  3.92
1    0.71       Good     D     SI1   56.8   62.0   2450  5.93  5.89  3.37
2    0.73    Premium     D     SI2   62.4   58.0   2519  5.72  5.67  3.56
3    0.90       Good     F     SI1   63.6   55.0   4712  6.15  6.12  3.90
4    0.42      Ideal     D    VVS2   62.5   57.0   1389  4.80  4.77  2.99
5    0.42  Very Good     G     VS2   62.6   57.0    847  4.76  4.80  2.99
6    1.33      Ideal     G    VVS2   62.6   57.0  12209  7.04  6.99  4.39
7    1.01       Good     E     SI2   63.3   58.0   4149  6.29  6.35  4.00
8    0.40      Ideal     E     VS1   61.1   57.0   1291  4.75  4.78  2.97
9    0.52    Premium     G     VS2   62.4   56.0   1577  5.19  5.16  3.23
10   1.11      Ideal     G    VVS2   61.8   57.0   8858  6.67  6.64  4.11
11   0.91    Premium     H     VS2   59.6   60.0   3853  6.29  6.25  3.74
12   1.20  Very Good     G    VVS1   61.8   55.0   9968  6.79  6.83  4.21
13   1.01      Ideal     E     VS1   61.6   57.0   7565  6.45  6.41  3.96
14   0.30  Very Good     G    VVS2   60.3   57.0    631  4.35  4.36  2.63
15   2.01      Ideal     I     SI2   62.1   57.0  12338  8.07  8.03  5.00
16   0.30      Ideal     F    VVS2   62.5   56.0    694  4.28  4.33  2.69
17   0.50    Premium     E     VS2   61.3   60.0   1746  5.11  5.07  3.12
18   1.01    Premium     E     SI2   62.5   60.0   4355  6.39  6.42  4.00
19   0.30  Very Good     F     VS1   60.9   63.0    704  4.26  4.31  2.61

##뽑은 sample들을 x, y, z 순으로 정렬해보자
x가 같은 경우 y를 key로, y가 같은 경우 z를 key로 사용

In [ ]:
samples.sort_values(by=['x','y','z'], ascending=[True, True, True])

       carat        cut color clarity  depth  table  price     x     y     z
29534   0.30  Very Good     F     VS1   60.9   63.0    704  4.26  4.31  2.61
29183   0.30      Ideal     F    VVS2   62.5   56.0    694  4.28  4.33  2.69
23025   0.30  Very Good     G    VVS2   60.3   57.0    631  4.35  4.36  2.63
42234   0.40      Ideal     E     VS1   61.1   57.0   1291  4.75  4.78  2.97
34002   0.42  Very Good     G     VS2   62.6   57.0    847  4.76  4.80  2.99
43166   0.42      Ideal     D    VVS2   62.5   57.0   1389  4.80  4.77  2.99
46168   0.50    Premium     E     VS2   61.3   60.0   1746  5.11  5.07  3.12
44291   0.52    Premium     G     VS2   62.4   56.0   1577  5.19  5.16  3.23
52475   0.73    Premium     D     SI2   62.4   58.0   2519  5.72  5.67  3.56
52039   0.71       Good     D     SI1   56.8   62.0   2450  5.93  5.89  3.37
10092   0.90       Good     F     SI1   63.6   55.0   4712  6.15  6.12  3.90
5530    0.91    Premium     H     VS2   59.6   60.0   3853  6.29  6.25  3.74
6965    1.01       Good     E     SI2   63.3   58.0   4149  6.29  6.35  4.00
7214    1.01    Premium     H     SI1   61.9   59.0   4191  6.35  6.32  3.92
8131    1.01    Premium     E     SI2   62.5   60.0   4355  6.39  6.42  4.00
18556   1.01      Ideal     E     VS1   61.6   57.0   7565  6.45  6.41  3.96
20535   1.11      Ideal     G    VVS2   61.8   57.0   8858  6.67  6.64  4.11
21899   1.20  Very Good     G    VVS1   61.8   55.0   9968  6.79  6.83  4.21
24063   1.33      Ideal     G    VVS2   62.6   57.0  12209  7.04  6.99  4.39
24159   2.01      Ideal     I     SI2   62.1   57.0  12338  8.07  8.03  5.00

##다시 30개의 sample을 뽑아보자 이번에는 price에 가중치를 두어 sample을 추출한다(Tip. weights)

In [ ]:
samples2 = data.sample(n=30, weights='price')
samples2

       carat        cut color clarity  depth  table  price     x     y     z
24295   1.07      Ideal     D    VVS2   60.3   56.0  12545  6.63  6.68  4.01
41209   0.51      Ideal     E     SI2   61.0   56.0   1205  5.20  5.16  3.16
20804   1.08      Ideal     G      IF   61.3   57.0   9035  6.62  6.59  4.05
19583   1.22      Ideal     G     VS2   61.4   56.0   8213  6.88  6.90  4.23
5708    0.25  Very Good     F    VVS2   59.4   57.0    575  4.10  4.12  2.44
26775   2.07      Ideal     J    VVS2   62.7   54.0  16617  8.12  8.17  5.11
1397    0.24      Ideal     G      IF   61.6   57.0    559  3.99  4.02  2.46
21774   1.51  Very Good     G     SI1   62.9   58.0   9841  7.25  7.28  4.57
22924   1.50  Very Good     F     SI1   63.4   58.0  10962  7.20  7.16  4.55
14558   1.00    Premium     D     SI1   62.5   59.0   5880  6.38  6.32  3.97
50904   0.72      Ideal     G     SI1   62.0   56.0   2318  5.75  5.71  3.55
25074   1.50  Very Good     G     VS1   60.2   58.0  13596  7.38  7.41  4.45
10011   1.01  Very Good     H     SI1   63.3   57.0   4707  6.41  6.36  4.04
23055   1.51  Very Good     I    VVS1   63.0   59.0  11088  7.24  7.30  4.58
24139   1.54    Premium     G     VS2   61.6   59.0  12308  7.46  7.40  4.58
10525   1.01       Good     D     SI2   63.6   57.0   4805  6.39  6.35  4.05
19657   1.17      Ideal     H      IF   61.0   53.0   8266  6.89  6.85  4.19
27509   2.02  Very Good     H     SI1   59.3   60.0  18236  8.14  8.21  4.85
27689   1.72    Premium     G    VVS2   61.8   60.0  18730  7.65  7.68  4.74
25072   2.01  Very Good     J     VS2   63.2   55.0  13596  7.97  8.04  5.07
1821    0.90       Good     I     SI2   60.7   58.0   3057  6.17  6.21  3.76
25402   2.05      Ideal     J     VS2   61.7   54.9  14111  8.16  8.24  5.05
1473    0.74      Ideal     E     VS2   62.7   54.0   2984  5.80  5.77  3.63
27645   2.01       Good     G     SI1   63.1   59.0  18572  7.98  8.03  5.05
23982   2.12    Premium     J     SI2   62.3   61.0  12140  8.21  8.16  5.10
17029   1.11      Ideal     E     SI1   61.1   57.0   6800  6.64  6.72  4.08
17752   1.19  Very Good     H     VS1   62.4   59.0   7147  6.73  6.79  4.22
27108   2.02  Very Good     D     SI2   62.3   56.0  17263  7.99  8.06  5.00
17619   1.16       Fair     F     VS1   57.8   67.0   7094  6.97  6.84  3.99
22311   1.21      Ideal     E     VS1   62.4   57.0  10351  6.75  6.83  4.24