<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/2.%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%A0%95%EB%A0%AC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)

**특정 열 값을 기준으로 정렬하기**

In [2]:
df.sort_values('a', ascending=False)  # ascending True는 오름차순, False는 내림차순

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13
  1  4   8  12

**열 이름 변경하기**

In [3]:
df.rename(columns={"c":"d"})  # c열의 이름을 d로 변경

     a   b   d
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**인덱스 값 초기화하기**

In [4]:
df.reset_index()

   n  v  a   b   c
0  d  1  4   8  12
1  d  2  5   9  13
2  e  1  6  10  14
3  e  2  7  11  15

**인덱스 순서대로 정렬하기**

In [5]:
df.sort_index()

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**특정 열 제거하기**

In [6]:
df.drop(columns=["a", "b"])

      c
n v
d 1  12
  2  13
e 1  14
  2  15