<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/3_%ED%96%89_%EC%B6%94%EC%B6%9C%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)

df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**맨 위의 행 출력하기**

In [2]:
df.head(2)  # 맨 위 2행만 출력

     a  b   c
n v
d 1  4  8  12
  2  5  9  13

**맨 아래 행 출력하기**

In [3]:
df.tail(2)  # 맨 아래 2행만 출력

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

**특정 열의 값을 추출하기**

In [4]:
df[df["a"]>4]  # a열 중 4보다 큰 값이 있을 경우 해당 행을 추출

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

**특정 열에 특정 값이 있을 경우 추출하기**

In [5]:
df[df["a"]==6]  # a열 중 6이 있을 경우 해당 행을 추출

     a   b   c
n v
e 1  6  10  14

**특정 열에 특정 값이 없을 경우 추출하기**

In [6]:
df[df["a"] != 5]  # a열 중 5가 없을 경우 해당 행을 추출

     a   b   c
n v
d 1  4   8  12
e 1  6  10  14
  2  7  11  15

**특정 열에 특정 숫자가 있는지 확인하기**

In [7]:
df[df["a"].isin([4])]

     a  b   c
n v
d 1  4  8  12

**특정 비율로 데이터 샘플링하기**

In [8]:
df.sample(frac=0.8)  # 실행할 때마다 정해진 비율만큼 랜덤하게 추출

     a   b   c
n v
d 2  5   9  13
  1  4   8  12
e 1  6  10  14

**특정 개수만큼 데이터 샘플링하기**

In [9]:
df.sample(n=3)  # 실행할 때마다 n에서 정한 만큼 랜덤하게 추출

     a   b   c
n v
e 1  6  10  14
d 2  5   9  13
  1  4   8  12

**특정 열에서 큰 순서대로 불러오기**

In [10]:
df.nlargest(3, 'a')  # a열에서 큰 순서대로 3개를 불러옴

     a   b   c
n v
e 2  7  11  15
  1  6  10  14
d 2  5   9  13

**특정 열에서 작은 순서대로 불러오기**

In [11]:
df.nsmallest(3, 'a')  # a열에서 작은 순서대로 3개를 불러옴

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14