<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/4_%EC%97%B4_%EC%B6%94%EC%B6%9C%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)

df

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**인덱스의 범위로 불러오기**

In [ ]:
df.iloc[1:4]  # 두번째 인덱스부터 순서대로 3개를 불러옴

     a   b   c
n v
d 2  5   9  13
e 1  6  10  14
  2  7  11  15

**첫 인덱스를 지정해 불러오기**

In [ ]:
df.iloc[2:]  # 세번째 인덱스부터 마지막 인덱스까지 불러옴

     a   b   c
n v
e 1  6  10  14
  2  7  11  15

**마지막 인덱스를 지정해 불러오기**

In [ ]:
df.iloc[:3]  # 처음부터 세번째 인덱스까지 불러옴

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14

**모든 인덱스 불러오기**

In [ ]:
df.iloc[:]

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**특정 열을 지정해 가져오기**

In [ ]:
df[['a','b']]  # a열과 b열을 가져옴

     a   b
n v
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11

**조건을 만족하는 열 가져오기**

In [ ]:
df.filter(regex='c')  # 열 이름에 c라는 문자가 포함되어 있으면 출력함

      c
n v
d 1  12
  2  13
e 1  14
  2  15

**특정 문자가 포함되지 않는 열 가져오기**

In [ ]:
df.filter(regex='^(?!c$).*')  # 열 이름에 c라는 문자가 포함되어 있지 않으면 출력함

     a   b
n v
d 1  4   8
  2  5   9
e 1  6  10
  2  7  11