<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/5_%ED%96%89%EA%B3%BC_%EC%97%B4_%EC%B6%94%EC%B6%9C%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.DataFrame(
    {"a": [4, 5, 6, 7],
     "b": [8, 9, 10, 11],
     "c": [12, 13, 14, 15]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)

**특정 행과 열을 지정해 가져오기**

In [ ]:
# df.loc[가져올 행, 가져올 열]
df.loc[:,'a':'c']  # 모든 인덱스에서 a열부터 c열까지 가져오라는 뜻

     a   b   c
n v
d 1  4   8  12
  2  5   9  13
e 1  6  10  14
  2  7  11  15

**인덱스로 특정 행과 열 가져오기**

In [ ]:
df.iloc[0:3,[0,2]]  # 0 인덱스부터 2 인덱스까지 0번째 열과 2번째 열을 가져오라는 의미 (첫 열이 0번째)

     a   c
n v
d 1  4  12
  2  5  13
e 1  6  14

**특정 열에서 조건을 만족하는 행과 열 가져오기**

In [ ]:
df.loc[df['a']>5, ['a','c']]  # a열 값이 5보다 큰 경우 a열과 c열을 출력하라는 뜻

     a   c
n v
e 1  6  14
  2  7  15

**인덱스를 이용해 특정 조건을 만족하는 값 불러오기**

In [ ]:
df.iat[1,2]  # 1번째 인덱스에서 2번째 열 값을 가져옴

13