<a href="https://colab.research.google.com/github/ChaelinL/Pandas_Study/blob/main/8_%EA%B2%B0%EC%B8%A1%EC%B9%98_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {"a": [4, 5, 6, np.nan],
     "b": [7, 8, np.nan, 9],
     "c": [10, np.nan, 11, 12]},
     index=pd.MultiIndex.from_tuples(
         [('d',1), ('d', 2), ('e', 1), ('e', 2)],
         names=['n', 'v']
     )
)
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   NaN
e 1  6.0  NaN  11.0
  2  NaN  9.0  12.0

**null 값인지 확인하기**

In [2]:
pd.isnull(df)

         a      b      c
n v
d 1  False  False  False
  2  False  False   True
e 1  False   True  False
  2   True  False  False

**null 값이 아닌지 확인하기**

In [3]:
pd.notnull(df)

         a      b      c
n v
d 1   True   True   True
  2   True   True  False
e 1   True  False   True
  2  False   True   True

**null 값이 있는 행 삭제하기**

In [4]:
df.dropna()

       a    b     c
n v
d 1  4.0  7.0  10.0

**null 값을 특정 값으로 대체하기**

In [5]:
df.fillna(13)  # null 값을 13으로 대체

        a     b     c
n v
d 1   4.0   7.0  10.0
  2   5.0   8.0  13.0
e 1   6.0  13.0  11.0
  2  13.0   9.0  12.0

**null 값을 특정 계산 결과로 대체하기**

In [6]:
df.fillna(df['a'].mean())  # null 값을 a열의 평균값으로 대체

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0   5.0
e 1  6.0  5.0  11.0
  2  5.0  9.0  12.0